apiVersion: apps/v1
kind: Deployment
metadata:
  name: pentalog
  namespace: pentalog
  labels:
    app: pentalog
spec:
  selector:
    matchLabels:
      app: pentalog
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "pentalog-sa"
        vault.hashicorp.com/agent-inject-secret-configuration.txt: "customers/pentalog/configuration/database"
      labels:
        app: pentalog
    spec:
      serviceAccountName: pentalog-sa
      containers:
        - name: orgchart
          image: jweissig/app:0.0.1