apiVersion: apps/v1
kind: Deployment
metadata:
  name: pentalog
  namespace: pentalog
  labels:
    app: pentalog
spec:
  selector:
    matchLabels:
      app: pentalog
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "pentalog-sa"
        vault.hashicorp.com/agent-inject-secret-database.json: "customers/pentalog/configuration/database"
        vault.hashicorp.com/secret-volume-path-database.json: "/app/config"
        vault.hashicorp.com/agent-inject-template-database.json: |
          {{- with secret "customers/pentalog/configuration/database" -}}
            {{- .Data.data | toJSONPretty }}
          {{- end }}
      labels:
        app: pentalog
    spec:
      serviceAccountName: pentalog-sa
      containers:
        - name: orgchart
          image: jweissig/app:0.0.1